version: '3.3'

services:
    nginx:
        image: nginx:alpine
        ports:
            - ${WEB_PORT}:80
        links:
            - fpm
        volumes:
            - ${HOST_APP_PATH}:${CONTAINER_APP_PATH}
            - ./logs:/var/log/nginx
            - ./conf:/etc/nginx/conf.d
    fpm:
        image: aden16rus/phpfpmext:xdebug
        volumes:
            - ${HOST_APP_PATH}:${CONTAINER_APP_PATH}
            - ./php:/usr/local/etc/php
    mysql:
        image: mysql:5.7
        ports:
            - ${DB_PORT}:3306
        volumes:
            - ./databases:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASS}
            - MYSQL_DATABASE=${DB_NAME}
    
    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
